/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiTrackRouteImport } from './routes/api.track'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ThoughtsSlugRouteImport } from './routes/thoughts.$slug'
import { Route as WritingsIndexRouteImport } from './routes/writings.index'
import { Route as WritingsSlugRouteImport } from './routes/writings.$slug'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin.analytics'
import { Route as AdminAdminContactsRouteImport } from './routes/_admin.admin.contacts'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminMediaRouteImport } from './routes/_admin.admin.media'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin.admin.projects'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminStructureRouteImport } from './routes/_admin.admin.structure'
import { Route as WritingsCollectionsCollectionRouteImport } from './routes/writings.collections.$collection'
import { Route as AdminAdminBlogsIndexRouteImport } from './routes/_admin.admin.blogs.index'
import { Route as AdminAdminBlogsNewRouteImport } from './routes/_admin.admin.blogs.new'
import { Route as AdminAdminPersonalizeIndexRouteImport } from './routes/_admin.admin.personalize.index'
import { Route as AdminAdminPersonalizeSectionRouteImport } from './routes/_admin.admin.personalize.$section'
import { Route as AdminAdminWritingsIndexRouteImport } from './routes/_admin.admin.writings.index'
import { Route as AdminAdminWritingsNewRouteImport } from './routes/_admin.admin.writings.new'
import { Route as WritingsCollectionsCollectionIndexRouteImport } from './routes/writings.collections.$collection.index'
import { Route as WritingsCollectionsCollectionChapterRouteImport } from './routes/writings.collections.$collection.$chapter'
import { Route as AdminAdminBlogsIdEditRouteImport } from './routes/_admin.admin.blogs.$id.edit'
import { Route as AdminAdminWritingsIdEditRouteImport } from './routes/_admin.admin.writings.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsSlugRoute = ThoughtsSlugRouteImport.update({
  id: '/thoughts/$slug',
  path: '/thoughts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/writings/',
  path: '/writings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/writings/$slug',
  path: '/writings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContactsRoute = AdminAdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMediaRoute = AdminAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminStructureRoute = AdminAdminStructureRouteImport.update({
  id: '/admin/structure',
  path: '/admin/structure',
  getParentRoute: () => AdminRoute,
} as any)
const WritingsCollectionsCollectionRoute =
  WritingsCollectionsCollectionRouteImport.update({
    id: '/writings/collections/$collection',
    path: '/writings/collections/$collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminBlogsIndexRoute = AdminAdminBlogsIndexRouteImport.update({
  id: '/admin/blogs/',
  path: '/admin/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogsNewRoute = AdminAdminBlogsNewRouteImport.update({
  id: '/admin/blogs/new',
  path: '/admin/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPersonalizeIndexRoute =
  AdminAdminPersonalizeIndexRouteImport.update({
    id: '/admin/personalize/',
    path: '/admin/personalize/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPersonalizeSectionRoute =
  AdminAdminPersonalizeSectionRouteImport.update({
    id: '/admin/personalize/$section',
    path: '/admin/personalize/$section',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminWritingsIndexRoute = AdminAdminWritingsIndexRouteImport.update({
  id: '/admin/writings/',
  path: '/admin/writings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminWritingsNewRoute = AdminAdminWritingsNewRouteImport.update({
  id: '/admin/writings/new',
  path: '/admin/writings/new',
  getParentRoute: () => AdminRoute,
} as any)
const WritingsCollectionsCollectionIndexRoute =
  WritingsCollectionsCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WritingsCollectionsCollectionRoute,
  } as any)
const WritingsCollectionsCollectionChapterRoute =
  WritingsCollectionsCollectionChapterRouteImport.update({
    id: '/$chapter',
    path: '/$chapter',
    getParentRoute: () => WritingsCollectionsCollectionRoute,
  } as any)
const AdminAdminBlogsIdEditRoute = AdminAdminBlogsIdEditRouteImport.update({
  id: '/admin/blogs/$id/edit',
  path: '/admin/blogs/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminWritingsIdEditRoute =
  AdminAdminWritingsIdEditRouteImport.update({
    id: '/admin/writings/$id/edit',
    path: '/admin/writings/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/contacts': typeof AdminAdminContactsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/structure': typeof AdminAdminStructureRoute
  '/writings/collections/$collection': typeof WritingsCollectionsCollectionRouteWithChildren
  '/admin/blogs/new': typeof AdminAdminBlogsNewRoute
  '/admin/personalize/$section': typeof AdminAdminPersonalizeSectionRoute
  '/admin/writings/new': typeof AdminAdminWritingsNewRoute
  '/writings/collections/$collection/$chapter': typeof WritingsCollectionsCollectionChapterRoute
  '/admin/blogs/': typeof AdminAdminBlogsIndexRoute
  '/admin/personalize/': typeof AdminAdminPersonalizeIndexRoute
  '/admin/writings/': typeof AdminAdminWritingsIndexRoute
  '/writings/collections/$collection/': typeof WritingsCollectionsCollectionIndexRoute
  '/admin/blogs/$id/edit': typeof AdminAdminBlogsIdEditRoute
  '/admin/writings/$id/edit': typeof AdminAdminWritingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/writings': typeof WritingsIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/contacts': typeof AdminAdminContactsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/structure': typeof AdminAdminStructureRoute
  '/admin/blogs/new': typeof AdminAdminBlogsNewRoute
  '/admin/personalize/$section': typeof AdminAdminPersonalizeSectionRoute
  '/admin/writings/new': typeof AdminAdminWritingsNewRoute
  '/writings/collections/$collection/$chapter': typeof WritingsCollectionsCollectionChapterRoute
  '/admin/blogs': typeof AdminAdminBlogsIndexRoute
  '/admin/personalize': typeof AdminAdminPersonalizeIndexRoute
  '/admin/writings': typeof AdminAdminWritingsIndexRoute
  '/writings/collections/$collection': typeof WritingsCollectionsCollectionIndexRoute
  '/admin/blogs/$id/edit': typeof AdminAdminBlogsIdEditRoute
  '/admin/writings/$id/edit': typeof AdminAdminWritingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/track': typeof ApiTrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/contacts': typeof AdminAdminContactsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/media': typeof AdminAdminMediaRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/structure': typeof AdminAdminStructureRoute
  '/writings/collections/$collection': typeof WritingsCollectionsCollectionRouteWithChildren
  '/_admin/admin/blogs/new': typeof AdminAdminBlogsNewRoute
  '/_admin/admin/personalize/$section': typeof AdminAdminPersonalizeSectionRoute
  '/_admin/admin/writings/new': typeof AdminAdminWritingsNewRoute
  '/writings/collections/$collection/$chapter': typeof WritingsCollectionsCollectionChapterRoute
  '/_admin/admin/blogs/': typeof AdminAdminBlogsIndexRoute
  '/_admin/admin/personalize/': typeof AdminAdminPersonalizeIndexRoute
  '/_admin/admin/writings/': typeof AdminAdminWritingsIndexRoute
  '/writings/collections/$collection/': typeof WritingsCollectionsCollectionIndexRoute
  '/_admin/admin/blogs/$id/edit': typeof AdminAdminBlogsIdEditRoute
  '/_admin/admin/writings/$id/edit': typeof AdminAdminWritingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/track'
    | '/blog/$slug'
    | '/thoughts/$slug'
    | '/writings/$slug'
    | '/admin/'
    | '/blog/'
    | '/writings/'
    | '/admin/analytics'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/structure'
    | '/writings/collections/$collection'
    | '/admin/blogs/new'
    | '/admin/personalize/$section'
    | '/admin/writings/new'
    | '/writings/collections/$collection/$chapter'
    | '/admin/blogs/'
    | '/admin/personalize/'
    | '/admin/writings/'
    | '/writings/collections/$collection/'
    | '/admin/blogs/$id/edit'
    | '/admin/writings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/track'
    | '/blog/$slug'
    | '/thoughts/$slug'
    | '/writings/$slug'
    | '/admin'
    | '/blog'
    | '/writings'
    | '/admin/analytics'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/structure'
    | '/admin/blogs/new'
    | '/admin/personalize/$section'
    | '/admin/writings/new'
    | '/writings/collections/$collection/$chapter'
    | '/admin/blogs'
    | '/admin/personalize'
    | '/admin/writings'
    | '/writings/collections/$collection'
    | '/admin/blogs/$id/edit'
    | '/admin/writings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/api/track'
    | '/blog/$slug'
    | '/thoughts/$slug'
    | '/writings/$slug'
    | '/admin/'
    | '/blog/'
    | '/writings/'
    | '/_admin/admin/analytics'
    | '/_admin/admin/contacts'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/media'
    | '/_admin/admin/projects'
    | '/_admin/admin/settings'
    | '/_admin/admin/structure'
    | '/writings/collections/$collection'
    | '/_admin/admin/blogs/new'
    | '/_admin/admin/personalize/$section'
    | '/_admin/admin/writings/new'
    | '/writings/collections/$collection/$chapter'
    | '/_admin/admin/blogs/'
    | '/_admin/admin/personalize/'
    | '/_admin/admin/writings/'
    | '/writings/collections/$collection/'
    | '/_admin/admin/blogs/$id/edit'
    | '/_admin/admin/writings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiTrackRoute: typeof ApiTrackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ThoughtsSlugRoute: typeof ThoughtsSlugRoute
  WritingsSlugRoute: typeof WritingsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  WritingsIndexRoute: typeof WritingsIndexRoute
  WritingsCollectionsCollectionRoute: typeof WritingsCollectionsCollectionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/$slug': {
      id: '/thoughts/$slug'
      path: '/thoughts/$slug'
      fullPath: '/thoughts/$slug'
      preLoaderRoute: typeof ThoughtsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/writings'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/writings/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/contacts': {
      id: '/_admin/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminAdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/media': {
      id: '/_admin/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/structure': {
      id: '/_admin/admin/structure'
      path: '/admin/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminAdminStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/writings/collections/$collection': {
      id: '/writings/collections/$collection'
      path: '/writings/collections/$collection'
      fullPath: '/writings/collections/$collection'
      preLoaderRoute: typeof WritingsCollectionsCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/blogs/': {
      id: '/_admin/admin/blogs/'
      path: '/admin/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminAdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blogs/new': {
      id: '/_admin/admin/blogs/new'
      path: '/admin/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminAdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/personalize/': {
      id: '/_admin/admin/personalize/'
      path: '/admin/personalize'
      fullPath: '/admin/personalize/'
      preLoaderRoute: typeof AdminAdminPersonalizeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/personalize/$section': {
      id: '/_admin/admin/personalize/$section'
      path: '/admin/personalize/$section'
      fullPath: '/admin/personalize/$section'
      preLoaderRoute: typeof AdminAdminPersonalizeSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/writings/': {
      id: '/_admin/admin/writings/'
      path: '/admin/writings'
      fullPath: '/admin/writings/'
      preLoaderRoute: typeof AdminAdminWritingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/writings/new': {
      id: '/_admin/admin/writings/new'
      path: '/admin/writings/new'
      fullPath: '/admin/writings/new'
      preLoaderRoute: typeof AdminAdminWritingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/writings/collections/$collection/': {
      id: '/writings/collections/$collection/'
      path: '/'
      fullPath: '/writings/collections/$collection/'
      preLoaderRoute: typeof WritingsCollectionsCollectionIndexRouteImport
      parentRoute: typeof WritingsCollectionsCollectionRoute
    }
    '/writings/collections/$collection/$chapter': {
      id: '/writings/collections/$collection/$chapter'
      path: '/$chapter'
      fullPath: '/writings/collections/$collection/$chapter'
      preLoaderRoute: typeof WritingsCollectionsCollectionChapterRouteImport
      parentRoute: typeof WritingsCollectionsCollectionRoute
    }
    '/_admin/admin/blogs/$id/edit': {
      id: '/_admin/admin/blogs/$id/edit'
      path: '/admin/blogs/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminAdminBlogsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/writings/$id/edit': {
      id: '/_admin/admin/writings/$id/edit'
      path: '/admin/writings/$id/edit'
      fullPath: '/admin/writings/$id/edit'
      preLoaderRoute: typeof AdminAdminWritingsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminContactsRoute: typeof AdminAdminContactsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminMediaRoute: typeof AdminAdminMediaRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStructureRoute: typeof AdminAdminStructureRoute
  AdminAdminBlogsNewRoute: typeof AdminAdminBlogsNewRoute
  AdminAdminPersonalizeSectionRoute: typeof AdminAdminPersonalizeSectionRoute
  AdminAdminWritingsNewRoute: typeof AdminAdminWritingsNewRoute
  AdminAdminBlogsIndexRoute: typeof AdminAdminBlogsIndexRoute
  AdminAdminPersonalizeIndexRoute: typeof AdminAdminPersonalizeIndexRoute
  AdminAdminWritingsIndexRoute: typeof AdminAdminWritingsIndexRoute
  AdminAdminBlogsIdEditRoute: typeof AdminAdminBlogsIdEditRoute
  AdminAdminWritingsIdEditRoute: typeof AdminAdminWritingsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminContactsRoute: AdminAdminContactsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminMediaRoute: AdminAdminMediaRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStructureRoute: AdminAdminStructureRoute,
  AdminAdminBlogsNewRoute: AdminAdminBlogsNewRoute,
  AdminAdminPersonalizeSectionRoute: AdminAdminPersonalizeSectionRoute,
  AdminAdminWritingsNewRoute: AdminAdminWritingsNewRoute,
  AdminAdminBlogsIndexRoute: AdminAdminBlogsIndexRoute,
  AdminAdminPersonalizeIndexRoute: AdminAdminPersonalizeIndexRoute,
  AdminAdminWritingsIndexRoute: AdminAdminWritingsIndexRoute,
  AdminAdminBlogsIdEditRoute: AdminAdminBlogsIdEditRoute,
  AdminAdminWritingsIdEditRoute: AdminAdminWritingsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WritingsCollectionsCollectionRouteChildren {
  WritingsCollectionsCollectionChapterRoute: typeof WritingsCollectionsCollectionChapterRoute
  WritingsCollectionsCollectionIndexRoute: typeof WritingsCollectionsCollectionIndexRoute
}

const WritingsCollectionsCollectionRouteChildren: WritingsCollectionsCollectionRouteChildren =
  {
    WritingsCollectionsCollectionChapterRoute:
      WritingsCollectionsCollectionChapterRoute,
    WritingsCollectionsCollectionIndexRoute:
      WritingsCollectionsCollectionIndexRoute,
  }

const WritingsCollectionsCollectionRouteWithChildren =
  WritingsCollectionsCollectionRoute._addFileChildren(
    WritingsCollectionsCollectionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiTrackRoute: ApiTrackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ThoughtsSlugRoute: ThoughtsSlugRoute,
  WritingsSlugRoute: WritingsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  WritingsIndexRoute: WritingsIndexRoute,
  WritingsCollectionsCollectionRoute:
    WritingsCollectionsCollectionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
